import type { FieldOpsStore } from './types';

const now = new Date('2026-03-12T09:00:00.000Z');

function iso(offsetHours: number) {
  return new Date(now.getTime() + offsetHours * 60 * 60 * 1000).toISOString();
}

export const fieldOpsSeed: FieldOpsStore = {
  profiles: [
    {
      id: 'profile-manager',
      fullName: 'Nora Klein',
      email: 'nora.klein@keptos.io',
      role: 'manager',
      phone: '+33 6 80 12 45 19',
      createdAt: iso(-120),
      updatedAt: iso(-2),
    },
    {
      id: 'profile-engineer',
      fullName: 'Amir Dahan',
      email: 'amir.dahan@keptos.io',
      role: 'engineer',
      phone: '+33 6 58 44 19 83',
      createdAt: iso(-120),
      updatedAt: iso(-2),
    },
  ],
  clients: [
    {
      id: 'client-alpine',
      name: 'Alpine Hotels Group',
      status: 'active',
      primaryContact: 'Maya Laurent',
      primaryEmail: 'maya.laurent@alpine-hotels.com',
      primaryPhone: '+33 1 40 19 20 21',
      contractType: 'managed-services',
      sla: 'Gold 4h / 8h',
      notes: 'High-touch hospitality estate with strict executive-floor Wi-Fi expectations.',
      createdAt: iso(-400),
      updatedAt: iso(-12),
    },
    {
      id: 'client-veridian',
      name: 'Veridian Retail France',
      status: 'active',
      primaryContact: 'Julien Morel',
      primaryEmail: 'julien.morel@veridian-retail.fr',
      primaryPhone: '+33 1 45 20 56 00',
      contractType: 'hybrid',
      sla: 'Silver NBD / 24h',
      notes: 'Mix of recurring store support and strategic network audits.',
      createdAt: iso(-320),
      updatedAt: iso(-6),
    },
    {
      id: 'client-orbit',
      name: 'Orbit Logistics',
      status: 'inactive',
      primaryContact: 'Lina Torres',
      primaryEmail: 'lina.torres@orbit-logistics.eu',
      primaryPhone: '+34 91 008 22 11',
      contractType: 'project',
      sla: 'Project mode',
      notes: 'Paused after warehouse migration, retained for history and reporting.',
      createdAt: iso(-600),
      updatedAt: iso(-72),
    },
  ],
  sites: [
    {
      id: 'site-alpine-paris',
      clientId: 'client-alpine',
      name: 'Paris HQ',
      address: '18 Rue de la Paix, Paris',
      localContact: 'Maya Laurent',
      localContactPhone: '+33 1 40 19 20 21',
      gpsLatitude: 48.8688,
      gpsLongitude: 2.3303,
      gpsPlaceholder: 'HQ main entrance beacon',
      status: 'operational',
      healthScore: 'green',
      createdAt: iso(-300),
      updatedAt: iso(-3),
    },
    {
      id: 'site-alpine-lyon',
      clientId: 'client-alpine',
      name: 'Lyon Riverside',
      address: '14 Quai Tilsitt, Lyon',
      localContact: 'Amin Farid',
      localContactPhone: '+33 4 78 11 88 21',
      gpsLatitude: 45.758,
      gpsLongitude: 4.8302,
      gpsPlaceholder: 'Reception desk geofence placeholder',
      status: 'maintenance',
      healthScore: 'orange',
      createdAt: iso(-280),
      updatedAt: iso(-2),
    },
    {
      id: 'site-veridian-lille',
      clientId: 'client-veridian',
      name: 'Lille Mega Store',
      address: '120 Boulevard Carnot, Lille',
      localContact: 'Julien Morel',
      localContactPhone: '+33 3 20 44 91 55',
      gpsLatitude: 50.6339,
      gpsLongitude: 3.0671,
      gpsPlaceholder: 'Store back-office entrance',
      status: 'at-risk',
      healthScore: 'red',
      createdAt: iso(-260),
      updatedAt: iso(-1),
    },
    {
      id: 'site-orbit-madrid',
      clientId: 'client-orbit',
      name: 'Madrid Warehouse',
      address: 'Calle Albares 12, Madrid',
      localContact: 'Lina Torres',
      localContactPhone: '+34 91 008 22 11',
      gpsLatitude: 40.4168,
      gpsLongitude: -3.7038,
      gpsPlaceholder: 'Dock gate GPS placeholder',
      status: 'inactive',
      healthScore: 'orange',
      createdAt: iso(-540),
      updatedAt: iso(-80),
    },
  ],
  engineers: [
    {
      id: 'engineer-amir',
      fullName: 'Amir Dahan',
      specialties: ['Network', 'Wi-Fi', 'Switching'],
      phone: '+33 6 58 44 19 83',
      email: 'amir.dahan@keptos.io',
      status: 'active',
      region: 'Paris / North',
      createdAt: iso(-220),
      updatedAt: iso(-4),
    },
    {
      id: 'engineer-lina',
      fullName: 'Lina Serrano',
      specialties: ['Desktop', 'Users', 'VIP Support'],
      phone: '+33 6 64 91 45 73',
      email: 'lina.serrano@keptos.io',
      status: 'active',
      region: 'Lyon / South-East',
      createdAt: iso(-220),
      updatedAt: iso(-8),
    },
    {
      id: 'engineer-thomas',
      fullName: 'Thomas Revault',
      specialties: ['Audit', 'Firewall', 'Service delivery'],
      phone: '+33 6 61 73 18 20',
      email: 'thomas.revault@keptos.io',
      status: 'on-leave',
      region: 'National',
      createdAt: iso(-220),
      updatedAt: iso(-12),
    },
  ],
  clientUsers: [
    {
      id: 'user-alpine-1',
      clientId: 'client-alpine',
      siteId: 'site-alpine-paris',
      fullName: 'Claire Dupont',
      email: 'claire.dupont@alpine-hotels.com',
      phone: '+33 1 40 19 21 10',
      department: 'Operations',
      jobTitle: 'Head of Front Office',
      notes: 'Requires after-hours intervention summaries.',
      recurringIncidents: ['Meeting room Wi-Fi drops', 'VIP printer queue delays'],
      createdAt: iso(-120),
      updatedAt: iso(-6),
    },
    {
      id: 'user-veridian-1',
      clientId: 'client-veridian',
      siteId: 'site-veridian-lille',
      fullName: 'Theo Martin',
      email: 'theo.martin@veridian-retail.fr',
      phone: '+33 3 20 44 91 12',
      department: 'Store IT',
      jobTitle: 'Retail Systems Supervisor',
      notes: 'Escalates quickly when PoS latency spikes.',
      recurringIncidents: ['ISP packet loss', 'PoS payment terminal disconnect'],
      createdAt: iso(-110),
      updatedAt: iso(-3),
    },
    {
      id: 'user-orbit-1',
      clientId: 'client-orbit',
      siteId: 'site-orbit-madrid',
      fullName: 'Raul Medina',
      email: 'raul.medina@orbit-logistics.eu',
      phone: '+34 91 008 22 18',
      department: 'Warehouse',
      jobTitle: 'Fulfillment Lead',
      notes: 'History retained for warehouse migration support.',
      recurringIncidents: ['Scanner roaming issues'],
      createdAt: iso(-180),
      updatedAt: iso(-60),
    },
  ],
  interventions: [
    {
      id: 'int-001',
      reference: 'INT-20260312-101',
      clientId: 'client-alpine',
      siteId: 'site-alpine-paris',
      engineerId: 'engineer-amir',
      type: 'preventive',
      status: 'in_progress',
      priority: 'medium',
      scheduledStartAt: iso(-1),
      scheduledEndAt: iso(1),
      actualStartAt: iso(-0.8),
      actualEndAt: null,
      durationMinutes: null,
      slaTargetAt: iso(4),
      internalComments: 'Quarterly network health review and AP optimization.',
      checkInAt: iso(-0.8),
      checkOutAt: null,
      checkInGpsPlaceholder: 'GPS capture pending mobile wrapper',
      checkOutGpsPlaceholder: null,
      createdAt: iso(-8),
      updatedAt: iso(-0.5),
    },
    {
      id: 'int-002',
      reference: 'INT-20260312-102',
      clientId: 'client-veridian',
      siteId: 'site-veridian-lille',
      engineerId: 'engineer-lina',
      type: 'network',
      status: 'todo',
      priority: 'critical',
      scheduledStartAt: iso(2),
      scheduledEndAt: iso(4),
      actualStartAt: null,
      actualEndAt: null,
      durationMinutes: null,
      slaTargetAt: iso(3),
      internalComments: 'Investigate ISP jitter reported by PoS lane 7 and 8.',
      checkInAt: null,
      checkOutAt: null,
      checkInGpsPlaceholder: null,
      checkOutGpsPlaceholder: null,
      createdAt: iso(-5),
      updatedAt: iso(-1),
    },
    {
      id: 'int-003',
      reference: 'INT-20260311-211',
      clientId: 'client-alpine',
      siteId: 'site-alpine-lyon',
      engineerId: 'engineer-lina',
      type: 'corrective',
      status: 'completed',
      priority: 'high',
      scheduledStartAt: iso(-26),
      scheduledEndAt: iso(-24),
      actualStartAt: iso(-25.8),
      actualEndAt: iso(-24.7),
      durationMinutes: 66,
      slaTargetAt: iso(-22),
      internalComments: 'Conference VLAN remediation.',
      checkInAt: iso(-25.8),
      checkOutAt: iso(-24.7),
      checkInGpsPlaceholder: 'Manual check-in placeholder',
      checkOutGpsPlaceholder: 'Manual check-out placeholder',
      createdAt: iso(-30),
      updatedAt: iso(-24.7),
    },
    {
      id: 'int-004',
      reference: 'INT-20260310-144',
      clientId: 'client-veridian',
      siteId: 'site-veridian-lille',
      engineerId: 'engineer-amir',
      type: 'audit',
      status: 'on_hold',
      priority: 'medium',
      scheduledStartAt: iso(-32),
      scheduledEndAt: iso(-30),
      actualStartAt: iso(-31.8),
      actualEndAt: null,
      durationMinutes: null,
      slaTargetAt: iso(-12),
      internalComments: 'Paused pending ISP maintenance window.',
      checkInAt: iso(-31.8),
      checkOutAt: null,
      checkInGpsPlaceholder: 'GPS placeholder enabled',
      checkOutGpsPlaceholder: null,
      createdAt: iso(-38),
      updatedAt: iso(-16),
    },
  ],
  interventionLogs: [
    {
      id: 'log-001',
      interventionId: 'int-001',
      kind: 'created',
      actor: 'Nora Klein',
      message: 'Intervention created from weekly preventive maintenance plan.',
      createdAt: iso(-8),
      updatedAt: iso(-8),
    },
    {
      id: 'log-002',
      interventionId: 'int-001',
      kind: 'check-in',
      actor: 'Amir Dahan',
      message: 'Check-in validated on site.',
      gpsPlaceholder: 'GPS capture pending mobile wrapper',
      createdAt: iso(-0.8),
      updatedAt: iso(-0.8),
    },
    {
      id: 'log-003',
      interventionId: 'int-002',
      kind: 'created',
      actor: 'Nora Klein',
      message: 'Urgent network intervention scheduled after retail incident burst.',
      createdAt: iso(-5),
      updatedAt: iso(-5),
    },
    {
      id: 'log-004',
      interventionId: 'int-003',
      kind: 'check-out',
      actor: 'Lina Serrano',
      message: 'Visit completed and client briefed.',
      gpsPlaceholder: 'Manual check-out placeholder',
      createdAt: iso(-24.7),
      updatedAt: iso(-24.7),
    },
  ],
  interventionReports: [
    {
      id: 'report-001',
      interventionId: 'int-003',
      diagnostic: 'Packet drops on conference VLAN traced to AP channel overlap.',
      probableCause: 'Uncoordinated AP replacement by local contractor.',
      actionsTaken: 'Retuned channels, updated power profile, validated roaming.',
      result: 'Stability restored; follow-up preventive survey advised in 30 days.',
      hardware: 'Cisco Catalyst AP set',
      software: 'Meraki dashboard policy profile',
      impactedUsers: 'Events team and executive meeting rooms',
      attachmentIds: ['attachment-001'],
      clientValidation: 'pending',
      pdfStatus: 'planned',
      createdAt: iso(-24.6),
      updatedAt: iso(-24.2),
    },
  ],
  networkReports: [
    {
      id: 'network-001',
      siteId: 'site-veridian-lille',
      interventionId: 'int-002',
      connectionType: 'Fiber',
      provider: 'Orange Business',
      perceivedQuality: 'Customer reports frequent stalls at payment terminals.',
      downloadMbps: 181,
      uploadMbps: 61,
      pingMs: 137,
      packetLossPct: 6.4,
      technicalRemarks: 'High jitter between 08:15 and 08:42, requires ISP ticket correlation.',
      healthScore: 'red',
      createdAt: iso(-1.5),
      updatedAt: iso(-1.2),
    },
    {
      id: 'network-002',
      siteId: 'site-alpine-lyon',
      interventionId: 'int-003',
      connectionType: 'Fiber backup LTE',
      provider: 'Bouygues Telecom',
      perceivedQuality: 'Mostly stable after AP remediation.',
      downloadMbps: 412,
      uploadMbps: 149,
      pingMs: 34,
      packetLossPct: 0.5,
      technicalRemarks: 'Backup LTE not used during normal hours.',
      healthScore: 'green',
      createdAt: iso(-24.5),
      updatedAt: iso(-24.3),
    },
  ],
  attachments: [
    {
      id: 'attachment-001',
      interventionId: 'int-003',
      reportId: 'report-001',
      name: 'conference-vlan-spectrum.jpg',
      fileType: 'photo',
      url: '/mock/attachments/conference-vlan-spectrum.jpg',
      createdAt: iso(-24.5),
      updatedAt: iso(-24.5),
    },
  ],
  integrations: [
    {
      id: 'integration-zendesk',
      platform: 'zendesk',
      name: 'Zendesk Support',
      status: 'planned',
      scope: 'Bidirectional ticket linkage',
      description: 'Prepare local interventions to map cleanly to external Zendesk tickets.',
      createdAt: iso(-80),
      updatedAt: iso(-6),
    },
    {
      id: 'integration-jira',
      platform: 'jira',
      name: 'Jira Service Management',
      status: 'ready',
      scope: 'Incident sync and asset context',
      description: 'Connector shell ready for JSM request and issue synchronization.',
      createdAt: iso(-80),
      updatedAt: iso(-4),
    },
    {
      id: 'integration-servicenow',
      platform: 'servicenow',
      name: 'ServiceNow ITSM',
      status: 'planned',
      scope: 'Enterprise accounts and CMDB references',
      description: 'Reserved for future enterprise contracts requiring CMDB traceability.',
      createdAt: iso(-80),
      updatedAt: iso(-5),
    },
    {
      id: 'integration-freshservice',
      platform: 'freshservice',
      name: 'Freshservice',
      status: 'paused',
      scope: 'Mid-market helpdesk mapping',
      description: 'Connector backlog item kept in architecture and admin catalog.',
      createdAt: iso(-80),
      updatedAt: iso(-2),
    },
  ],
  integrationAccounts: [
    {
      id: 'account-jira-fr',
      integrationId: 'integration-jira',
      accountName: 'Keptos EU Service Desk',
      externalWorkspace: 'keptos-itops',
      status: 'connected',
      createdAt: iso(-48),
      updatedAt: iso(-3),
    },
    {
      id: 'account-zendesk-alpha',
      integrationId: 'integration-zendesk',
      accountName: 'Alpha Workspace Placeholder',
      externalWorkspace: 'alpha-zendesk',
      status: 'pending',
      createdAt: iso(-36),
      updatedAt: iso(-6),
    },
  ],
  externalRecords: [
    {
      id: 'external-001',
      platform: 'jira',
      localEntityType: 'intervention',
      localEntityId: 'int-004',
      externalId: '10042',
      externalKey: 'JSM-421',
      syncStatus: 'warning',
      lastSyncAt: iso(-10),
      payloadSnapshot: {
        summary: 'Lille Mega Store network audit',
        priority: 'medium',
        status: 'waiting for provider',
      },
      createdAt: iso(-30),
      updatedAt: iso(-10),
    },
  ],
  syncLogs: [
    {
      id: 'sync-001',
      integrationId: 'integration-jira',
      platform: 'jira',
      entityType: 'intervention',
      entityId: 'int-004',
      syncStatus: 'warning',
      direction: 'push',
      message: 'Status pushed, but external SLA field missing from account mapping.',
      executedAt: iso(-10),
      createdAt: iso(-10),
      updatedAt: iso(-10),
    },
    {
      id: 'sync-002',
      integrationId: 'integration-zendesk',
      platform: 'zendesk',
      entityType: 'intervention',
      entityId: 'int-002',
      syncStatus: 'queued',
      direction: 'push',
      message: 'Connector shell queued for future outbound sync.',
      executedAt: iso(-1),
      createdAt: iso(-1),
      updatedAt: iso(-1),
    },
    {
      id: 'sync-003',
      integrationId: 'integration-jira',
      platform: 'jira',
      entityType: 'network_report',
      entityId: 'network-001',
      syncStatus: 'success',
      direction: 'pull',
      message: 'Imported external diagnostics metadata for packet loss incident.',
      executedAt: iso(-3),
      createdAt: iso(-3),
      updatedAt: iso(-3),
    },
  ],
  interventionTypes: [
    { id: 'itype-1', name: 'Preventive', code: 'preventive' },
    { id: 'itype-2', name: 'Corrective', code: 'corrective' },
    { id: 'itype-3', name: 'Emergency', code: 'emergency' },
    { id: 'itype-4', name: 'Network', code: 'network' },
    { id: 'itype-5', name: 'Audit', code: 'audit' },
    { id: 'itype-6', name: 'User', code: 'user' },
  ],
  statusCatalog: [
    { id: 'status-1', entity: 'intervention', value: 'todo', label: 'To do' },
    { id: 'status-2', entity: 'intervention', value: 'in_progress', label: 'In progress' },
    { id: 'status-3', entity: 'intervention', value: 'on_hold', label: 'On hold' },
    { id: 'status-4', entity: 'intervention', value: 'completed', label: 'Completed' },
    { id: 'status-5', entity: 'intervention', value: 'cancelled', label: 'Cancelled' },
    { id: 'status-6', entity: 'site', value: 'operational', label: 'Operational' },
    { id: 'status-7', entity: 'site', value: 'maintenance', label: 'Maintenance' },
    { id: 'status-8', entity: 'site', value: 'at-risk', label: 'At risk' },
    { id: 'status-9', entity: 'engineer', value: 'active', label: 'Active' },
    { id: 'status-10', entity: 'engineer', value: 'on-leave', label: 'On leave' },
  ],
  slaCatalog: [
    { id: 'sla-1', name: 'Gold 4h / 8h', responseHours: 4, resolutionHours: 8, coverage: '24/7' },
    { id: 'sla-2', name: 'Silver NBD / 24h', responseHours: 8, resolutionHours: 24, coverage: 'Business hours' },
    { id: 'sla-3', name: 'Bronze 24h / 72h', responseHours: 24, resolutionHours: 72, coverage: 'Business hours' },
  ],
  generalSettings: {
    companyName: 'Keptos FieldOps',
    commandCenterName: 'Keptos Command Layer',
    supportEmail: 'ops@keptos.io',
    timezone: 'Europe/Paris',
  },
};
