ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "backgroundColor" TEXT;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "surfaceColor" TEXT;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "cardColor" TEXT;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "foregroundColor" TEXT;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "mutedColor" TEXT;
